services:
    app:
        container_name: PizzaSYS
        build:
            context: ./
            dockerfile: ./dev.DockerFile
        ports:
            - 3000:3000
        volumes:
            - ./src:/app/src
    db:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            MONGO_INITDB_DATABASE: pizzasys
            ME_CONFIG_BASICAUTH: false